apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-sanity-cms-v3
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-sanity-cms-v3
spec:
  image: ghcr.io/navikt/imagename:tag
  ingresses:
    - https://dagpenger.intern.nav.no/sanity