name: Sanity Cloud Backup Routine
on:
  #schedule:
    # Runs at 04:00 UTC every thursday
    #- cron: "0 4 * * 4"
  workflow_dispatch:

jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install @sanity/cli
      - name: Copy production dataset to cloud backup
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_CLOUD_BACKUP_TOKEN }}
        run: npx sanity dataset copy production prod-backup