name: Build, push, and deploy

on: [push]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - run: npm run build
      - uses: navikt/frontend/actions/spa-deploy/v1@main
        with:
          app-name: dp-sanity-cms-v3
          team-name: teamdagpenger
          source: ./dist
          ingress: https://dagpenger.intern.nav.no/
          environment: prod
          nais-deploy-apikey: ${{ secrets.NAIS_DEPLOY_APIKEY }}
