name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - uses: actions/setup-node@v4
        if: steps.node_modules.outputs.cache-hit != 'true'
        with:
          node-version: '24.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm ci --ignore-scripts
        if: steps.node_modules.outputs.cache-hit != 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Install Sanity CLI
        run: npm install -g @sanity/cli

      - name: Install Sanity
        run: sanity install

      - name: Build project
        run: sanity build

      - name: Deploy Sanity
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
        run: sanity deploy
